### ISSUE TITLE
SXWN9000 for text node rule

### ISSUE THREAD

**Issue by AirQuick** [dmj/schxslt#11]
When I have a rule on text
```xml
<sch:rule context="text()">
```

then the compiled stylesheet generates a warning
```console
Warning at char 7 in xsl:apply-templates/@select on line 142 column 66 of stage-3.xsl:
  SXWN9000: The child axis starting at a text node will never select anything
Warning at char 11 in xsl:apply-templates/@select on line 142 column 66 of stage-3.xsl:
  SXWN9000: The attribute axis starting at a text node will never select anything
```

Could this be avoided?

Using Saxon 9.9.0.2.

**Comment by AirQuick** [comment]
Replacing https://github.com/dmj/schxslt/blob/086a08182532eac7376dceaf191c3046bf498542/src/xslt/compile.xsl#L258
with something like
```xml
          <call-template name="schxslt:handle-attr-and-children"/>
```
and relocating `xsl:apply-templates` into that named template might work in this particular case, although ugly...
Just my quick thought.

**Comment by dmj** [comment]
This curently works, indeed. But I don't think that this is a viable solution: Saxon issues the warning during static analysis. It might be just a matter of time until Saxon catches up.

Maybe suppressing Saxon warnings alltogether is an option?

If not, we could utilize ​@‍use-when and create different paths depedning on the xsl:vendor system property. But this should be the last resort.

**Comment by dmj** [comment]
Addendum: With queryBinding xslt3 the solution would be xsl:mode on-no-match=shallow-skip. I currently need the apply-templates call b/c the built-in template rule for elements ignores the attribute axis.

**Comment by dmj** [comment]
No, this is not true. Still need to apply to @‍* __when an element has matched__.

**Comment by AirQuick** [comment]
Right, the viability depends entirely on Saxon's evolution.
I don't know what the best solution would be... In general I would hesitate to suppress warnings, for fear of overlooking helpful ones.

**Comment by dmj** [comment]
This problem is solved: SchXslt now uses "ex-post rule match selection" by default. I.e.: The validation stylesheet chains rule templates with xsl:next-match.
