### ISSUE TITLE
Text node not reported in svrl:successful-report/@location

### ISSUE THREAD

**Issue by AirQuick** [dmj/schxslt#7]
I just ran the latest master over `flowers.sch` (and `flowers.xml`) in [`Schematron-step-by-step\Sampels\Flowers\`](https://www.oxygenxml.com/events/2018/webinar_creating_schematron_rules_and_quick_fixes.html) and got this kind of results

```xml
   <svrl:successful-report location="/topic[1]/body[1]/section[3]/p[2]/ul[1]/li[3]/p[1]"
...
```

for this rule

```xml
    <sch:rule context="text()">
      <sch:report test="matches(., '(http|www)\S+') 
...
```

Is it intentional that the `svrl:successful-report/@location` path stopped at `p` and doesn't include `text()`?

**Comment by dmj** [comment]
No, this is an bug. Thanks for testing!
